version: "3.9"

services:
    postgres:
        image: postgres:13.2-alpine
        container_name: pg_rockelivery
        hostname: pg_rockelivery
        volumes:
            - postgres_data:/var/lib/postgresql/data
        ports:
            - 5432:5432
        environment:
            - POSTGRES_DB=rockelivery_dev
            - POSTGRES_PASSWORD=postgres
            - POSTGRES_USER=postgres

volumes:
    postgres_data:
